apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Базовый namespace; в overlay/prod переопределяется на messager-prod.
namespace: messager

labels:
  - pairs:
      app.kubernetes.io/part-of: messager
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - minio-secret.yaml
  - csi-s3-secret.yaml
  - postgres-init-cm.yaml
  - users-migrations-cm.yaml
  - messages-migrations-cm.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - migrate-users-job.yaml
  - migrate-messages-job.yaml
  - minio.yaml
  - s3-pvc.yaml
  - create-bucket-job.yaml
  - user-service.yaml
  - message-service.yaml
  - bff.yaml
  - frontend.yaml
  - ingress.yaml
